### ISSUE TITLE
New Metric: which permutation of systems do I need to use to get full coverage?

### ISSUE THREAD

**Issue by mikix** [sync-for-science/qualifier#1]
From a researcher point of view, I might want to know "If I'm going to be analyzing Conditions, which systems do I need to look at to get the best coverage?"

(e.g. "snomed get me 90% of conditions, but snomed+icd10 get me 100%, so those two are all I need to focus on in my study")

This would look similar to [prior art in this repo](https://github.com/sync-for-science/qualifier/blob/8202ded/app/reports/system_permutations.py). Going through permutations of systems, throwing away ones that didn't improve percentages.

This is probably not a powerset-style CUBE but rather a c_resources_per_pt-style line-level metric.

(This kind of language was part of `c_term_coverage` originally, but that metric is morphing into simply grouping multiple systems together and kicking the find-the-best-set-of-permutations idea into a separate metric - which is what this issue is asking for.)

**Comment by gotdan** [comment]
From a naming perspective, maybe we keep `c_term_coverage` for "which systems do I need to look at to get the best coverage" metric and add something like `c_system_use` as the metric that provides counts by groups of systems?

**Comment by mikix** [comment]
OK I buy that - can add to my PR

**Comment by mikix** [comment]
This way we could also leave #2 in c_term_coverage too (since it won't be a cube style output)

**Comment by gotdan** [comment]
In terms of metric naming then (obviously the most important part of data quality), I'm realizing they should probably be c_system_coverage and c_system_use then?

**Comment by mikix** [comment]
Sure, now's a good time for a rename... but you do use `_term_` in a lot of metric names. A global rename like `s/_term_/_system_/g`?

**Comment by mikix** [comment]
Actually, some of those `_term_` metrics are about the _value_...

**Comment by gotdan** [comment]
Yeah, I was assuming we'd leave those as `_term_`, but maybe they should become `_code_` so we'd be using the FHIR `system` and `code` consistently.

**Comment by mikix** [comment]
Will close this - it shouldn't be needed now that I'm not taking over c_system_coverage with my own separate interpretation. :smile:
